compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmScopes:
  sand-enterpriseai:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAlwaysAuth: true
    npmAuthToken: "${NODE_AUTH_TOKEN-}"
